# version: "3.8"
services:
  postgres:
    profiles: ["db_api"]
    image: postgres:13
    container_name: node-onboarding-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: node-onboarding-db-postgres-volume